/* 
 * SMS Fusion API
 *
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type OutOfCredit struct {

	// Description of error
	Error_ string `json:"error,omitempty"`
}
